# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidgetAction



class Ui_HelpWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 521, 491))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        self.menuHow_to = QtWidgets.QMenu(self.menubar)
        self.menuHow_to.setObjectName("menuHow_to")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHow_to.menuAction())
        a1 = QWidgetAction(self.menuHow_to)
        a1.triggered.connect(self.populateInfo1)
        self.menuHow_to.addAction(a1)
        a2 = QWidgetAction(self.menuHow_to)
        a2.triggered.connect(self.populateInfo2)
        self.menuHow_to.addAction(a2)
        a1.setText("How to")
        a2.setText("Credits")
        self.label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def populateInfo1(self):
        result = ""
        result += "Here you can find a guide to the PortScanner!\n\n"
        result += "To start you need to select a hostname.\n"
        result += "Not all hostnames are valid so let's make sure you choose a valid one.\n\n"
        result += "The hostname must be:\n"
        result += "a)A valid IP address.\n"
        result += "Good example: 192.168.0.195\nBad Example: 256.1235.23.1\n"
        result += "Make sure you are acquainted with the structed of an IP address.\n"
        result += "b)A valid DNS.\n"
        result += "Example: google.com.\n\n"
        result += "The port range must be:\n"
        result += "a)A valid numeric integer between [0-65535].\n"
        result += "b)An increasing range or a single port.\n"
        result += "Good examples: 80, [80,80], [80,90].\n"
        result += "Bad examples: ssh, 65536, [80,79].\n\n"
        result += "As you may have observed you have some options to choose from.\n"
        result += "Explanation for each option:\n"
        result += "1)You can select the TCP option to perform a TCP scan.\n"
        result += "2)You can select the UDP option to perform a UDP scan.\n"
        result += "3)You can select them both if you want both types of scans.\n"
        result += "4)You can select the Show only open ports to filter the closed ports out of the result.\n"
        result += "5)You can click on a found port to check if the database has any information about it.\n\n"
        result += "Example:\n"
        result += "Scan for TCP/UDP port 80 on host google.com.\n"
        result += "Click on the port 80 result and you will find out information about the http port."
        self.label.setText(result)

    def populateInfo2(self):
        result = ""
        result += "Credits:\n"
        result += "Application designed and implemented by:\nTudor Ardelean\n"
        result += "Babes-Bolyai University Cluj-Napoca \nFaculty of Mathematics and Computer Science \nSpecialization english \nSupervisor Conf. Dr. Suciu Mihai\n\n"
        result += "Using QtDesigner and PyQt5 under the terms of GNU GPL"
        self.label.setText(result)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Help"))
        self.label.setText(_translate("MainWindow", "Choose an option from the menu!"))
        self.menuHow_to.setTitle(_translate("MainWindow", "Menu"))
