# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from registerScreen import Ui_RegisterWindow
from service.Service import Service
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from interface.portScreen import Ui_PortWindow


class Ui_MainWindow(object):
    def __init__(self):
        self.service = Service()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 80, 51, 31))
        self.label.setObjectName("label")
        self.textEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_username.setGeometry(QtCore.QRect(90, 170, 211, 31))
        self.textEdit_username.setObjectName("textEdit_username")
        self.textEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_password.setGeometry(QtCore.QRect(90, 240, 211, 31))
        self.textEdit_password.setObjectName("textEdit_password")
        self.textEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 51, 16))
        self.label_3.setObjectName("label_3")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(150, 300, 91, 21))
        self.loginButton.setObjectName("loginButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 340, 91, 21))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.loginButton.clicked.connect(self.login)
        self.pushButton.clicked.connect(self.registerWindow)

    def retranslateUi(self,MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Port Scanner"))
        self.label.setText(_translate("MainWindow", "Welcome!"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "Register"))

    def registerWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RegisterWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def switch_windows(self,username):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PortWindow(username)
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def login(self):
        # self.label_3.setText("AAAAAA")
        username = self.textEdit_username.text()
        password = self.textEdit_password.text()
        if username == "" or password == "":
            msg = QMessageBox()
            msg.setWindowTitle("Something went wrong.")
            msg.setText("Username or Password fields are empty!")
            msg.setIcon(QMessageBox.Information)
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msg.exec_()
            return
        if self.service.checkCredentials(username, password):
            self.switch_windows(username)
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Something went wrong.")
            msg.setText("Username or Password fields are are incorrect!")
            msg.setIcon(QMessageBox.Information)
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msg.exec_()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
