# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QAbstractItemView
from time import sleep
from service.Service import Service
from interface.helpScreen import Ui_HelpWindow

from PyQt5 import QtTest
class Ui_PortWindow(object):
    def __init__(self, username=None):
        self.username = username
        self.service = Service()
    def setupUi(self, PortWindow):
        PortWindow.setObjectName("PortWindow")
        PortWindow.resize(838, 497)
        PortWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(PortWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_hostname = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_hostname.setGeometry(QtCore.QRect(30, 100, 251, 31))
        self.textEdit_hostname.setObjectName("textEdit_hostname")
        self.textEdit_lower_port = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_lower_port.setGeometry(QtCore.QRect(310, 100, 61, 31))
        self.textEdit_lower_port.setObjectName("textEdit_lower_port")
        self.textEdit_upper_port = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_upper_port.setGeometry(QtCore.QRect(390, 100, 61, 31))
        self.textEdit_upper_port.setObjectName("textEdit_upper_port")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(520, 100, 111, 31))
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 70, 61, 20))
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(660, 100, 141, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.resultListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.resultListWidget.setGeometry(QtCore.QRect(30, 160, 411, 301))
        self.resultListWidget.setObjectName("resultListWidget")
        self.detailsBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.detailsBrowser.setGeometry(QtCore.QRect(470, 160, 341, 301))
        self.detailsBrowser.setObjectName("detailsBrowser")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(740, 10, 75, 23))
        self.logoutButton.setObjectName("logoutButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 140, 131, 17))
        self.checkBox.setObjectName("checkBox")

        self.checkBoxUDP = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxUDP.setGeometry(QtCore.QRect(460, 97, 41, 17))
        self.checkBoxUDP.setObjectName("checkBoxUDP")
        self.checkBoxTCP = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxTCP.setGeometry(QtCore.QRect(460, 120, 41, 17))
        self.checkBoxTCP.setObjectName("checkBoxTCP")

        self.checkBoxTCP.setChecked(True)
        self.checkBoxTCP.setChecked(True)

        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(650, 10, 75, 23))
        self.helpButton.setObjectName("helpButton")
        PortWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PortWindow)
        self.statusbar.setObjectName("statusbar")
        PortWindow.setStatusBar(self.statusbar)
        self.progressBar.setValue(0)

        self.retranslateUi(PortWindow)
        QtCore.QMetaObject.connectSlotsByName(PortWindow)
        self.startButton.clicked.connect(self.startScan)
        self.resultListWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.resultListWidget.itemActivated.connect(self.populateDetails)
        self.logoutButton.clicked.connect(self.clearListWidget)
        self.helpButton.clicked.connect(self.helpWindow)
        self.detailsBrowser.setText("Hello " + self.username + "! \nPlease access the help button to learn how to use this!")

    def helpWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HelpWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def populateDetails(self):
        information = self.resultListWidget.currentItem().text().split()[3]
        self.detailsBrowser.setText(str(self.service.getInformationForPorts(information)))

    def clearListWidget(self):
        self.resultListWidget.clear()
        self.detailsBrowser.clear()

    def startScan(self):
        self.progressBar.setValue(0)
        hostname = self.textEdit_hostname.text()
        port_low = self.textEdit_lower_port.text()
        port_high = self.textEdit_upper_port.text()
        if hostname == "" or port_low == "":
            msg = QMessageBox()
            msg.setWindowTitle("Something went wrong.")
            msg.setText("Hostname and lower port limit cannot be empty!")
            msg.setIcon(QMessageBox.Information)
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msg.exec_()
            return
        if port_high == "":
            port_high = port_low
        if self.checkBoxTCP.isChecked():
            try:
                resultTCP = self.service.scanTCP(hostname,port_low,port_high)
            except Exception as e:
                msg = QMessageBox()
                msg.setWindowTitle("Something went wrong!")
                msg.setText("TCP:"+str(e))
                msg.setIcon(QMessageBox.Information)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                msg.exec_()
                return

        if self.checkBoxUDP.isChecked():
            try:
                resultUDP = self.service.scanUDP(hostname,port_low,port_high)
            except Exception as e:
                msg = QMessageBox()
                msg.setWindowTitle("Something went wrong!")
                msg.setText("UDP: "+str(e))
                msg.setIcon(QMessageBox.Information)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                msg.exec_()
                return

        if self.checkBoxTCP.isChecked():
            if self.checkBox.isChecked():
                self.service.discardClosedPorts(resultTCP)
            share = 100/len(resultTCP)
            if share < 10:
                waittimmer = 500
            else:
                waittimmer = 2000
            a=0
            for r in resultTCP:
               a = a + share
               QtTest.QTest.qWait(waittimmer)
               self.progressBar.setValue(a)
               self.resultListWidget.addItem(r)

        if self.checkBoxUDP.isChecked():
            if self.checkBox.isChecked():
                self.service.discardClosedPorts(resultTCP)
            share = 100/len(resultUDP)
            if share < 10:
                waittimmer = 500
            else:
                waittimmer = 2000
            a=0
            for r in resultUDP:
               a = a + share
               QtTest.QTest.qWait(waittimmer)
               self.progressBar.setValue(a)
               self.resultListWidget.addItem(r)


        self.progressBar.setValue(100)




    def retranslateUi(self, PortWindow):
        _translate = QtCore.QCoreApplication.translate
        PortWindow.setWindowTitle(_translate("PortWindow", "Port Scanner"))
        self.startButton.setText(_translate("PortWindow", "Start"))
        self.label.setText(_translate("PortWindow", "Hostname:"))
        self.label_2.setText(_translate("PortWindow", "Port Range:"))
        self.logoutButton.setText(_translate("PortWindow", "Clear"))
        self.helpButton.setText(_translate("PortWindow", "Help"))
        self.checkBox.setText(_translate("PortWindow","Show only open ports"))
        self.checkBoxTCP.setText(_translate("PortWindow", "TCP"))
        self.checkBoxUDP.setText(_translate("PortWindow", "UDP"))

