# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from service.Service import Service

class Ui_RegisterWindow(object):
    def __init__(self):
        self.service=Service()
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(399, 411)
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_registerUser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_registerUser.setGeometry(QtCore.QRect(160, 320, 75, 23))
        self.pushButton_registerUser.setObjectName("pushButton_registerUser")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(130, 170, 141, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(130, 240, 141, 21))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 60, 111, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 140, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 210, 61, 16))
        self.label_3.setObjectName("label_3")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)
        self.pushButton_registerUser.clicked.connect(self.register)

    def register(self):
        username = self.lineEdit_username.text()
        password = self.lineEdit_password.text()
        if username == "" or password == "":
            msg = QMessageBox()
            msg.setWindowTitle("Something went wrong.")
            msg.setText("Username or Password fields are empty!")
            msg.setIcon(QMessageBox.Information)
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msg.exec_()
            return
        try:
            if self.service.checkRegister(username):
                msg = QMessageBox()
                msg.setWindowTitle("Something went wrong.")
                msg.setText("Username already exists!")
                msg.setIcon(QMessageBox.Information)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                msg.exec_()
                return
        except Exception:
            self.service.register(username,password)
            msg = QMessageBox()
            msg.setWindowTitle("Confirmation.")
            msg.setText("User created!")
            msg.setIcon(QMessageBox.Information)
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            r=msg.exec_()
            return



    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Register"))
        self.pushButton_registerUser.setText(_translate("RegisterWindow", "Register"))
        self.label.setText(_translate("RegisterWindow", "Please register below:"))
        self.label_2.setText(_translate("RegisterWindow", "Username:"))
        self.label_3.setText(_translate("RegisterWindow", "Password:"))
